### Práctica 1: procesado básico de datos.

- Grupo: 
    - Jesús Matos Torres.
    - Carlos Santana Esplá.


## Ejercicio 1: Codificador de valores simbólicos a numéricos.



In [11]:
class CodificarEtiqueta:
    def __init__(self):
        self.lista_final = []
        self.dic = {}

    def inicializar(self, lista):
        self.lista = lista
        self.contador = 0
        for i in self.lista:
            if not i in self.dic:
                self.dic[i] = self.contador
                self.contador += 1
                
    def codificador(self, lista):
        self.lista_final.clear()
        self.lista = lista
        for i in self.lista:
            if i in self.dic:
                self.lista_final.append(self.dic[i])
            else:
                raise TypeError("valor simbólico no definido")
        return self.lista_final
                
    def decodificador(self, lista):
        self.lista_final.clear()
        self.lista = lista
        for i in self.lista:
            l1 = len(self.lista_final)
            for j in self.dic:
                if i == self.dic[j]:
                    self.lista_final.append(j)
            if l1 == len(self.lista_final):
                raise TypeError("valor fuera de rango")
        return self.lista_final

midic = CodificarEtiqueta()
midic.inicializar(["a","b","c","d","e"])
resultado_codificador = midic.codificador(["a", "c", "a", "e"])
print(resultado_codificador)
resultado_decodificador = midic.decodificador([3, 1, 2, 4, 1, 0])
print(resultado_decodificador)

[0, 2, 0, 4]
['d', 'b', 'c', 'e', 'b', 'a']


### Explicación:

A la hora de resolver el código, utilizamos diccionarios para añadir cada código simbólico como un código numérico, lo que nos facilitará la resolución en los métodos codificador y decodificador. Esto es debido a que, cada método accede al diccionario y transforma su valor numérico a simbólico o viseversa. 


### Ejercicio 2: escala de valores.

In [21]:
import numpy as np

class EscalarValores:
    def __init__(self):
        self.min = -1
        self.max = 1
        self.n = []
        self.m = []

    def inicializar(self, matriz):
        i = 0
        columna = []
        while i < len(matriz[0]):
            for fila in matriz:
                columna.append(fila[i])

            min_colum = min(columna)
            max_colum = max(columna)
            
            self.m.append(((self.max - self.min))/(max_colum-min_colum))
            self.n.append(((self.min*max_colum)-(self.max*min_colum))/(max_colum-min_colum))

            columna.clear()
            i += 1
            
        
    def escalar(self, matriz):
        for i in range(len(matriz)):
            for j in range(len(matriz[i])):
                matriz[j][i] = self.m[i]*matriz[j][i]+self.n[i]
        return matriz
        
    def escalar_inv(self, matriz):
        for i in range(len(matriz)):
            for j in range(len(matriz[i])):
                matriz[j][i] = (matriz[j][i]-self.n[i])/(self.m[i])
        return matriz
        
mimat = EscalarValores()
a = np.array([[8,4,1],[1,2,5],[9,2,3]], float)
mimat.inicializar(a)
res = mimat.escalar(a)
print(res)
print(mimat.escalar_inv(res))

a = np.array([[3,3,2],[5,4,3],[2,4,4]], float)
res = mimat.escalar(a)
print(res)
print(mimat.escalar_inv(res))

a = np.array([[7,1,0],[12,2,0],[4,5,40]], float)
res = mimat.escalar(a)
print(res)
print(mimat.escalar_inv(res))

[[ 0.75  1.   -1.  ]
 [-1.   -1.    1.  ]
 [ 1.   -1.    0.  ]]
[[8. 4. 1.]
 [1. 2. 5.]
 [9. 2. 3.]]
[[-0.5   0.   -0.5 ]
 [ 0.    1.    0.  ]
 [-0.75  1.    0.5 ]]
[[3. 3. 2.]
 [5. 4. 3.]
 [2. 4. 4.]]
[[ 0.5  -2.   -1.5 ]
 [ 1.75 -1.   -1.5 ]
 [-0.25  2.   18.5 ]]
[[ 7.  1.  0.]
 [12.  2.  0.]
 [ 4.  5. 40.]]


### Explicación:

En inicializar calculamos la pendiente y la desviación y lo guardamos como variable global utilizando constructores.

Dentro de los métodos de escalar y escalar_inv y utilizando la fórmula de la recta, hallamos la matriz escalada e inversa en los diferentes ejemplos.