# Práctica 9: Clasificador Bayesiano.

- Grupo 1:
    - Jesús María Matos Torres.
    - Carlos Santana Esplá.

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.simplefilter("ignore")

## Ejercicio 1: Clasificación de mensajes como spam con Naive Bayes.


In [9]:
df_bin = pd.read_csv('./datos practicas/Aprendizaje-Automatico-I-main/Práctica 9/spam_preprocesado_binario.csv')
df_real = pd.read_csv('./datos practicas/Aprendizaje-Automatico-I-main/Práctica 9/spam_preprocesado_reales.csv')

x_bin = df_bin.iloc[:,1:]
y_bin = df_bin.iloc[:,0]

x_real = df_real.iloc[:,1:]
y_real = df_real.iloc[:,0]

        xb_train, xb_test, yb_train, yb_test = train_test_split(x_bin, y_bin, test_size=0.3, train_size=0.7)
xr_train, xr_test, yr_train, yr_test = train_test_split(x_real, y_real, test_size=0.3, train_size=0.7)

nb = [GaussianNB(), MultinomialNB(), ComplementNB(), BernoulliNB()]

for i in range(len(nb)):
    clf = nb[i]
    yb_pred = clf.fit(xb_train, yb_train).predict(xb_test)
    scoreb = accuracy_score(yb_pred, yb_test)
    
    yr_pred = clf.fit(xr_train, yr_train).predict(xr_test)
    scorer = accuracy_score(yr_pred, yr_test)
    
    print('Para el clasificador', nb[i], 'obtenemos para el conjunto de datos binarios una tasa de acierto de', scoreb,
         'y para el conjunto de datos real', scorer)
    print('Sus matrices de confusión serán respectivamente:')
    print(confusion_matrix(yb_test, yb_pred))
    print(confusion_matrix(yr_test, yr_pred))

Para el clasificador GaussianNB() obtenemos para el conjunto de datos binarios una tasa de acierto de 0.6985645933014354 y para el conjunto de datos real 0.7416267942583732
Sus matrices de confusión serán respectivamente:
[[963 494]
 [ 10 205]]
[[1010  423]
 [   9  230]]
Para el clasificador MultinomialNB() obtenemos para el conjunto de datos binarios una tasa de acierto de 0.9766746411483254 y para el conjunto de datos real 0.9683014354066986
Sus matrices de confusión serán respectivamente:
[[1442   15]
 [  24  191]]
[[1429    4]
 [  49  190]]
Para el clasificador ComplementNB() obtenemos para el conjunto de datos binarios una tasa de acierto de 0.9497607655502392 y para el conjunto de datos real 0.944377990430622
Sus matrices de confusión serán respectivamente:
[[1389   68]
 [  16  199]]
[[1352   81]
 [  12  227]]
Para el clasificador BernoulliNB() obtenemos para el conjunto de datos binarios una tasa de acierto de 0.9772727272727273 y para el conjunto de datos real 0.977272727272727

- Tras varias iteraciones, determinamos lo siguiente de cada clasificador:
    
    - GaussianNB: Este clasificador suele ser usado para datos cuya verosimilitud sigue una distribición normal, para este ejercicio, nos da una mejor precisión con el conjunto de datos reales que para el conjunto de datos binario con una diferencia de entre 2% y 5%.
    
    - MultinomialNB: el uso de este clasificador es para analizar la cantidad de apariciones de un valor o una palabra, por lo que suele funcionar mejor para datos reales, para nuestro ejercicio esta hipótesis no se corrobora, ya que el accuracy_score de los datos reales es menor que el de los datos binario siendo una diferencia muy pequeña después de varias iteraciones.
    
    - ComplementNB: sin embargo, el clasificador complementNB, está relacionado con el anterior, su diferencia es que en este caso las clases están desbalanceadas, es decir, no hay la misma cantidad de datos para cada clase, por lo que los datos reales como en el anterior, deberían tener una mejor precisión, sin embargo esto no es así, aunque la diferencia entre las precisiones de ambos conjuntos de datos es ínfima.
    
    - BernoulliNB: suele ser útil para características booleanas, por ende, la precisión de los datos binarios debería ser bastante mejor. A pesar de esto, aunque vemos como la percisión de los datos binarios es mejor, la diferencia es muy pequeña. 

## Ejercicio 2: Comparación de clasificación de mensajes spam.

In [14]:
clasif = [Perceptron(), LogisticRegression(), SVC(), KNeighborsClassifier()]
tabla = []

for i in range(len(clasif)):
    tabla2 = []
    tabla2.append(clasif[i])
    
    clf = clasif[i]
    yb_pred = clf.fit(xb_train, yb_train).predict(xb_test)
    tabla2.append(accuracy_score(yb_pred, yb_test))
    
    yr_pred = clf.fit(xr_train, yr_train).predict(xr_test)
    tabla2.append(accuracy_score(yr_pred, yr_test))
    
    tabla.append(tabla2)

df = pd.DataFrame(tabla, columns=['Clasificador', 'Conjunto Binario', 'Conjunto Real'])
print(df.to_string(index=False))

          Clasificador  Conjunto Binario  Conjunto Real
          Perceptron()          0.969498       0.974282
  LogisticRegression()          0.977871       0.966507
                 SVC()          0.980263       0.978469
KNeighborsClassifier()          0.937201       0.923445


- Ahora analizaremos los clasificadores usados en las otras prácticas:
    
    - Perceptrón: sabiendo que la clasificación por perceptron funciona mejor con datos binarios, observamos como para nuestro ejercicio, esto no se corrobora, ya que la presición de los datos reales, es mayor que la de los datos binarios, como vemos en la tabla.
    
    - Regresión logística: partiendo de la base que la regresión logística se puede utilizar para ambos conjuntos de datos, aunque se adapta mejor a los datos binarios como se puede analizar en la solución del ejercicio, teniendo un accuracy_score mayor en ese conjunto de datos (binario). 
    
    - SVC: este clasificador también tiene buena aceptación en ambos conjunto de datos y también se corrobora con el ejercicio, ya que la diferencia entre ambas tasas de acierto es bastante pequeña. Además, este es el clasificador con mejor precisión.
    
    - Vecino más cercano: teniendo en cuenta, que el clasificador de vecino más cercano, como el clasificador anterior, funciona para ambos conjuntos de datos, nos sorprende que la diferencia entre la precisión de los diferentes conjuntos de datos, es mayor de lo esperado, ciertamente, esta diferencia no es elevada, tampoco es tan cercana como el clasificador SVC, que sería lo esperado.